export enum HomeworkTypes {
  LIST_REQUEST = "LIST_REQUEST",
  LIST_REQUEST_SUCCESS = "LIST_REQUEST_SUCCESS",
  LIST_REQUEST_FAIL = "LIST_REQUEST_FAIL",

  /**
   * REGISTER
   */

  REGISTER_HOMEWORK = "REGISTER_HOMEWORK",
  REGISTER_HOMEWORK_SUCCESS = "REGISTER_HOMEWORK_SUCCESS",
  REGISTER_HOMEWORK_FAIL = "REGISTER_HOMEWORK_FAIL",

  /**
   * EDIT
   */

  START_EDIT = "START_EDIT",

  /**
   * UPDATE
   */

  UPDATE_HOMEWORK_REQUEST = "UPDATE_HOMEWORK_REQUEST",
  UPDATE_HOMEWORK_REQUEST_SUCCESS = "UPDATE_HOMEWORK_REQUEST_SUCCESS",
  UPDATE_HOMEWORK_REQUEST_FAIL = "UPDATE_HOMEWORK_REQUEST_FAIL",
  /**
   * DELETE
   */
  DELETE_HOMEWORK_REQUEST = "DELETE_HOMEWORK_REQUEST",
  DELETE_HOMEWORK_REQUEST_SUCCESS = "DELETE_HOMEWORK_REQUEST_SUCCESS",
  DELETE_HOMEWORK_REQUEST_FAIL = "DELETE_HOMEWORK_REQUEST_FAIL",
}
