export enum CourseTypes {
  COURSE_ALL_REQUEST = "COURSE_ALL_REQUEST",
  COURSE_ALL_REQUEST_SUCCESS = "COURSE_ALL_REQUEST_SUCCESS",
  COURSE_ALL_REQUEST_FAIL = "COURSE_ALL_REQUEST_FAIL",

  /**
   * UPDATE
   */

  COURSE_EDIT = "COURSE_EDIT",

  /**
   * Delete suave
   */

  COURSE_DELETE_REQUEST = "COURSE_DELETE_REQUEST",
  COURSE_DELETE_REQUEST_SUCCESS = "COURSE_DELETE_REQUEST_SUCCESS",
  COURSE_DELETE_REQUEST_FAIL = "COURSE_DELETE_REQUEST_FAIL",

  /**
   * REGISTER
   */

  COURSE_REGISTER_REQUEST = "COURSE_REGISTER_REQUEST",
  COURSE_REGISTER_REQUEST_SUCCESS = "COURSE_REGISTER_REQUEST_SUCCESS",
  COURSE_REGISTER_REQUEST_FAIL = "COURSE_REGISTER_REQUEST_FAIL",

  /**
   * UPDATE
   */
  COURSE_UPDATE_REQUEST = "COURSE_UPDATE_REQUEST",
  COURSE_UPDATE_REQUEST_SUCCESS = "COURSE_UPDATE_REQUEST_SUCCESS",
  COURSE_UPDATE_REQUEST_FAIL = "COURSE_UPDATE_REQUEST_FAIL",
}
